"""Generate web/notes_data.json: detected notes per clip (audio analysis).

Runs the pitch tracker over each extracted wav and dumps the note events so
the web UI can show 'notes played at these times' per clip and map them onto
the fretboard.
"""
import sys, os, json
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from src.audio_notes import read_wav, detect_pitch_chunks, segment_notes, freq_to_midi

ROOT = os.path.join(os.path.dirname(__file__), "..")
AUDIO_DIR = os.path.join(ROOT, "data", "audio")

CLIPS = [
    ("fast_guitar_solo", "FAST_GUITAR_SOLO.webm", os.path.join(AUDIO_DIR, "solo.wav")),
    ("guitar_picks", "Demonstration_of_26_Guitar_Picks.webm", os.path.join(AUDIO_DIR, "picks.wav")),
]


def midi_to_name(m):
    names = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
    octave = m // 12 - 1
    return names[m % 12] + str(octave)


def main():
    out = {"clips": []}
    for key, video, wav in CLIPS:
        if not os.path.exists(wav):
            out["clips"].append({"id": key, "video": video, "notes": [],
                                 "error": "audio not extracted"})
            continue
        sr, data = read_wav(wav)
        chunks = detect_pitch_chunks(data, sr, rms_gate=0.004)
        notes = segment_notes(chunks, min_dur=0.07, semitone_tol=0.8)
        # keep only confident, meaningful-length notes
        pts = [{
            "start": round(n["start"], 2),
            "end": round(n["end"], 2),
            "midi": n["midi"],
            "name": midi_to_name(n["midi"]),
            "freq": round(n["freq"], 1),
            "conf": round(n["conf"], 2),
            "dur": round(n["end"] - n["start"], 2),
        } for n in notes
            if n["conf"] >= 0.5 and (n["end"] - n["start"]) >= 0.08]
        out["clips"].append({"id": key, "video": video, "notes": pts})
        print(f"{key}: {len(pts)} notes")

    path = os.path.join(ROOT, "web", "notes_data.json")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        json.dump(out, f, indent=1)
    # also emit an inline JS bundle so the page works over file:// (no fetch CORS)
    with open(os.path.join(ROOT, "web", "notes_data.js"), "w") as f:
        f.write("/* auto-generated by build_notes_json.py */\n")
        f.write("window.NOTES_DATA = " + json.dumps(out) + ";\n")
    print("wrote", path, "and notes_data.js")


if __name__ == "__main__":
    main()
