/* auto-generated sample MIDI (C-Am-F-G) for offline demo */
window.SAMPLE_MIDI64 = 'TVRoZAAAAAYAAQABAeBNVHJrAAAAaQD/UQMHoSAA/wMGZ3VpdGFyAJA8ZABAZABDZI8AgDwAAEAAAEMAAJA5ZAA8ZABAZI8AgDkAADwAAEAAAJA1ZAA5ZAA8ZI8AgDUAADkAADwAAJA3ZAA7ZAA+ZI8AgDcAADsAAD4AAP8vAA==';
window.SAMPLE_NAME = 'C-Am-F-G (cream.mid)';
